# ~/.config/starship.toml

add_newline = false
command_timeout = 1000

format = """
$character\
$status\
$os$hostname\
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$python\
$aws\
$golang\
$java\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$docker_context\
$battery\
[](#1C3A5E)$time[ ](#1C3A5E)$cmd_duration
[└─>](bold green) """


continuation_prompt = '▶▶ '

[character]
disabled = true
success_symbol = "✅ "
error_symbol = "🔥 "

[status]
disabled = false
success_symbol = "✅"
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 75
style = 'bold red'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = '[$duration](bold yellow)'

# ---

[os]
format = '[$symbol](bold white)'
disabled = false

[os.symbols]
Ubuntu = '🐧 '
Linux = '🐧 '
Windows = '🪟 '
Macos = '󰀵 '

# Shows the hostname
[hostname]
ssh_only = true
format = 'on [$ssh_symbol $hostname](bold yellow) '
disabled = false
ssh_symbol = ""

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '../'
# fish_style_pwd_dir_length = 2
home_symbol = '󰋜 ~'
read_only_style = '197'
read_only = '  '
format = 'at [$path]($style)[$read_only]($read_only_style) '

[directory.substitutions]
'/mnt/c/Users/mlack' = 'win-󰋜'
'/mnt/memory_alpha/docker-apps' = '-apps'

# Shows current git branch
[git_branch]
symbol = " "
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold green'

# Shows current git status
[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '

[sudo]
disabled = false
format = '[as $symbol ]($style)'
symbol ="🧙"
style = 'bold white'

[username]
disabled = false
show_always = false
format = '[as $user ]($style)'

# ---

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = true
style='bold dimmed white'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = " "

[package]
disabled = true
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rlang]
symbol = "󰟔 "

[rust]
symbol = " "

[scala]
symbol = " "