[ids]
*

[main]
capslock = layer(mod)
rightalt = layer(dia)
# rightcontrol = overload(control, sysrq)
102nd = overload(control, esc)  # iso extra key '\' '|' (or '<' '>' on german keyboard)

[dia]
# a = G-q
q = G-q
# o = G-p
p = G-p
# u = G-y
y = G-y
s = G-s
e = G-5
5 = G-5
` = G-S-;

[mod]
h = left
j = down
k = up
l = right
u = home
i = end
[ = pageup
' = pagedown
n = backspace
y = del
; = enter

a = mouse1
s = mouse2
